# Generated by Django 6.1.1 on 2026-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='disease',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
