# Generated by Django 6.1.1 on 2026-09-19 19:22

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_detection_confidence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to=detection.models.detection_image_path
            ),
        ),
    ]
